### ISSUE TITLE
add HDF5 / NeXuS Reader

### ISSUE THREAD

**Issue by paskino** [vais-ral/CILViewer#103]
Take inspiration from     https://blog.kitware.com/developing-hdf5-readers-using-vtkpythonalgorithm/

**Comment by lauramurgatroyd** [comment]
Current progress on this draft PR: https://github.com/vais-ral/CILViewer/pull/111

**Comment by lauramurgatroyd** [comment]
#111 added a HDF5 reader and resample reader. 

https://github.com/vais-ral/CILViewer/issues/131 addresses the issue of nexus reader
