### ISSUE TITLE
move to TomographicImaging?

### ISSUE THREAD

**Issue by paskino** [vais-ral/CILViewer#120]

**Comment by paskino** [comment]
Probably requires a new shiny name, @gfardell @lauramurgatroyd

**Comment by gfardell** [comment]
vivaCT (vivacity) Voxalized-Image Visualisation and Analysis for CT
voraCT (voracity) Voxalized Object Rendering and Analysis for CT
RAPTOR Really Awesome Plug-in Tomographic Object Renderer

**Comment by gfardell** [comment]
VORTEX - Voxalized Object Renderer for Tomography something something

**Comment by paskino** [comment]
Visir- Visualisation for Image Reconstruction
Ivan - Interactive Visualization and ANalysis tool

**Comment by gfardell** [comment]
VORTEX - Voxalized Object Renderer for Tomographic Excellence

**Comment by paskino** [comment]
Or
Voxelised Object Renderer for Tomography Expecially X-rays

**Comment by lauramurgatroyd** [comment]
Voxelised Object Renderer for Tomography EXploration is the current favourite

**Comment by DanicaSTFC** [comment]
I think we should move this and I do not like the name vortex because it has nothing to do with vortices :)

**Comment by DanicaSTFC** [comment]
Duplicated in https://github.com/orgs/TomographicImaging/projects/7/views/7?pane=issue&itemId=61437830
