### ISSUE TITLE
Make a viewer app

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CILViewer#160]
Should have a file menu that allows user to select 2 images and view them in 2D

**Comment by lauramurgatroyd** [comment]
For this to work we need to make the new io.py file: #162

**Comment by paskino** [comment]
I have a working implementation that might be useful at https://github.com/paskino/CIL-work/blob/master/RemoteViewer/TwoLinkedViewersCentralWidgetCompare.py

It requires something to understand the type of file to open.

**Comment by lauramurgatroyd** [comment]
Closed by #338
