### ISSUE TITLE
Do we need variables to be self.__ in resample and cropped readers?

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CILViewer#191]
Having the double underscore causes problems with inheritance and means we have to repeat a lot of code.

E.g. In the metaimage resample reader, we modify the method for setting the filename:
https://github.com/vais-ral/CILViewer/blob/150ba6fd1f811c76729cf86099b0fb773e7c9967/Wrappers/Python/ccpi/viewer/utils/conversion.py#L1186-L1196
What this does is it modifies the `self.__FileName` in the `cilMetaImageResampleReader`: 
https://github.com/vais-ral/CILViewer/blob/150ba6fd1f811c76729cf86099b0fb773e7c9967/Wrappers/Python/ccpi/viewer/utils/conversion.py#L1106-L1116

But it doesn't modify the `self.__FileName` in the `cilBaseResampleReader`:
https://github.com/vais-ral/CILViewer/blob/150ba6fd1f811c76729cf86099b0fb773e7c9967/Wrappers/Python/ccpi/viewer/utils/conversion.py#L594-L603

This means that if we call self.GetFileName() it returns None (the default value in the cilBaseResampleReader), so we have to redefine GetFileName() in the cilMetaImageResampleReader:
https://github.com/vais-ral/CILViewer/blob/150ba6fd1f811c76729cf86099b0fb773e7c9967/Wrappers/Python/ccpi/viewer/utils/conversion.py#L1197-L1198

This is similar for many other variables so we have a lot of repeated code.

If our variables did not have the double underscore out front, we wouldn't need to redefine the Get methods in the child classes.

**Comment by lauramurgatroyd** [comment]
The answer is instead to use super to call methods in parent:

```python   
def SetFileName(self, value):
        # in the case of an mha file, data is stored in the same file.
        if value != 'LOCAL':
            if not os.path.exists(value):
                raise ValueError('File does not exist!', value)

        if value != self.GetFileName():
            super(cilMetaImageResampleReader, self).SetFileName(value)
            self.ReadMetaImageHeader()
            self.Modified()```

**Comment by paskino** [comment]
I think it's an error of mine. I intended to create _private variables_, but ended up creating _class private_ variables, see [here](https://docs.python.org/3/tutorial/classes.html#private-variables).

So, I suppose the real fix would be to use a single `_` and use the class (possibly inherited) mutators, rather than the parent class', because 

```python
super(cilMetaImageResampleReader, self).SetFileName(value)
``` 
is particularly cumbersome as compared to 
```python
self.SetFileName(value)
```
