### ISSUE TITLE
Can we ship an example image with the CILViewer?

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CILViewer#218]
Almost all of the [examples](https://github.com/vais-ral/CILViewer/tree/master/Wrappers/Python/examples) require an image file.

Like with CIL, can we ship some example image with CILViewer so the examples can easily be run?

**Comment by paskino** [comment]
Sure. The head image is from [VTK Data](https://github.com/open-cv/VTKData/tree/master/Data/headsq). Check the license and ship it!

**Comment by lauramurgatroyd** [comment]
The only license I could find was this, which seems to just refer to the software, not specifically data

https://github.com/open-cv/VTKData/blob/master/Copyright.txt

**Comment by lauramurgatroyd** [comment]
closed by #223
