### ISSUE TITLE
HDF5SubsetReader: does it work and how?

### ISSUE THREAD

**Issue by paskino** [vais-ral/CILViewer#240]
I don't seem to understand how the `HDF5SubsetReader` is supposed to work if it doesn't inherit from `HDF5Reader` and even in this case it looks like it needs some work. `RequestData` isn't really doing anything. 

https://github.com/vais-ral/CILViewer/blob/1298c546e6e79203b1ad40c7a7e02d1d656f6921/Wrappers/Python/ccpi/viewer/utils/hdf5_io.py#L184-L243

**Comment by lauramurgatroyd** [comment]
It does work, but it is confusing and not like our other readers. It is based on this: https://blog.kitware.com/developing-hdf5-readers-using-vtkpythonalgorithm/ and takes the output from the HDF5Reader as an input

https://github.com/vais-ral/CILViewer/blob/1298c546e6e79203b1ad40c7a7e02d1d656f6921/Wrappers/Python/test/test_hdf5.py#L72-L80

**Comment by paskino** [comment]
So, in reality it is a modifyer of the `HDF5Reader`?

It's pretty powerful. I suggest to add that piece of code to the docstring.

**Comment by lauramurgatroyd** [comment]
yes. Ok, will do
