### ISSUE TITLE
trame viewer: sliders do not work well

### ISSUE THREAD

**Issue by paskino** [vais-ral/CILViewer#256]
Tested with the head they work well, but I tested with 2 other dataset and they don't seem to respond correctly.

Why is this here? Can't we just use the actual values and have say 200 steps?

https://github.com/vais-ral/CILViewer/blob/41ed704abb9dd62a2ba420d6554c370319cc0c69/Wrappers/Python/ccpi/web_viewer/trame_viewer.py#L334-L345

**Comment by lauramurgatroyd** [comment]
closing this because now https://github.com/vais-ral/CILViewer/issues/307 has been opened, and the issue with the sliders not responding correctly with other datasets was closed by #276
