### ISSUE TITLE
Linker Error due to GetSliceOrientation being renamed to getSliceOrientation only on CILViewer

### ISSUE THREAD

**Issue by paskino** [vais-ral/CILViewer#274]
A new error popped up in my [iDVC ](https://github.com/TomographicImaging/iDVC/tree/tiff_import)app with [`tiff_cropped_reader` ](https://github.com/vais-ral/CILViewer/tree/tiff_cropped_reader)branch.

```
File "C:\Apps\miniconda3\envs\idvc_dev8\lib\site-packages\ccpi\viewer\viewerLinker.py", line 311, in __call__
    if (self.sourceVtkViewer.getSliceOrientation() != self.targetVtkViewer.getSliceOrientation()):
AttributeError: 'CILViewer2D' object has no attribute 'getSliceOrientation'
'Linked2DInteractorStyle' object has no attribute 'getSliceOrientation'
```

`getSliceOrientation` is a method of `CILViewer` https://github.com/vais-ral/CILViewer/blob/6f698b786a412a5d29475f0cf70c05bf589117e4/Wrappers/Python/ccpi/viewer/CILViewer.py#L546-L547

but on the `CILViewer2D` it is still called 
https://github.com/vais-ral/CILViewer/blob/6f698b786a412a5d29475f0cf70c05bf589117e4/Wrappers/Python/ccpi/viewer/CILViewer2D.py#L1741-L1742

**Comment by paskino** [comment]
Also got
```
Traceback (most recent call last):
  File "C:\Apps\miniconda3\envs\idvc_dev8\lib\site-packages\ccpi\viewer\viewerLinker.py", line 329, in __call__
    self.targetVtkViewer.setSliceColorWindowLevel(window, level)
AttributeError: 'CILViewer2D' object has no attribute 'setSliceColorWindowLevel'
```

**Comment by lauramurgatroyd** [comment]
will be resolved by https://github.com/vais-ral/CILViewer/pull/270
