### ISSUE TITLE
environment.yml

### ISSUE THREAD

**Issue by paskino** [vais-ral/CILViewer#297]
IS this wrongly indented?

https://github.com/vais-ral/CILViewer/blob/c9d8604ef7accd5d6eec68b888f2a4396254270c/docker/web-app/environment.yml#L5-L8

**Comment by lauramurgatroyd** [comment]
I think the docker action would be more broken if the indenting was wrong.

But I fixed it on this branch anyway where the docker action currently fails due to some issues with importing the version
https://github.com/vais-ral/CILViewer/blob/resampling_cli/docker/web-app/environment.yml

**Comment by lauramurgatroyd** [comment]
changing the indenting made no difference to the action so I'm closing this

**Comment by paskino** [comment]
The error in that workflow are 2 and weird.

```
E   ModuleNotFoundError: No module named 'ccpi.viewer.version'
__________________ ERROR collecting test/test_cli_resample.py __________________
ImportError while importing test module '/root/source_code/Wrappers/Python/test/test_cli_resample.py'.
Hint: make sure your test modules/packages have valid Python names.

E   ImportError: cannot import name 'SaveRenderToPNG' from partially initialized module 'ccpi.viewer.utils.io' (most likely due to a circular import) (/root/source_code/Wrappers/Python/ccpi/viewer/utils/io.py)
```

Looks like the viewer is not correctly installed?
