### ISSUE TITLE
ImageWriter doesn't write out with file extension set in FileFormat variable

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CILViewer#323]
If the file format is one of these, it writes out as 'hdf5'. If we set the file format to 'nxs' for example, we should write out with extension 'nxs'.
https://github.com/vais-ral/CILViewer/blob/007e2ef2304f2fac270618bc7ebbca8e7c14fe7f/Wrappers/Python/ccpi/viewer/utils/io.py#L647-L649

**Comment by paskino** [comment]
the fix should be quite easy?

```python
 if self._FileFormat in ['nxs', 'h5', 'hdf5', '']: 
     self._FileName = file_name + '.' + self._FileFormat
     writer = self._GetHDF5Writer() 
```

**Comment by lauramurgatroyd** [comment]
yep, I had already made that fix locally, just hadn't made the PR yet
