### ISSUE TITLE
If we add a widget with the same name as an existing widget, what should happen to the existing widget?

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CILViewer#342]
Currently it continues to exist but there is no reference to it in the dictionary of widgets.

We should either throw an error saying that the widget already exists, or we should delete the existing widget with that name.

https://github.com/vais-ral/CILViewer/blob/28591187707b1a80ebbd3224abec86fc09ebe4ad/Wrappers/Python/ccpi/viewer/CILViewerBase.py#L365-L367

**Comment by paskino** [comment]
I think it should throw an error.

**Comment by lauramurgatroyd** [comment]
Closed by #343
