### ISSUE TITLE
failing unit test: pytest and QApplication

### ISSUE THREAD

**Issue by paskino** [vais-ral/CILViewer#367]
`QApplication` is a singleton and some unit tests fail with 
```
RuntimeError: Please destroy the QApplication singleton before creating a new QApplication instance.
```

In particular this happens if one runs both [`test_viewer_main_windows.py`](https://github.com/vais-ral/CILViewer/blob/master/Wrappers/Python/test/test_viewer_main_windows.py) and [`test_ui_dialogs.py`](https://github.com/vais-ral/CILViewer/blob/master/Wrappers/Python/test/test_ui_dialogs.py)

The following commands fails running the second test. The third command fails once the second of the 2 test files is run, i.e. generally 
`test_viewer_main_windows.py`

```
python -m pytest  test\test_viewer_main_windows.py test\test_ui_dialogs.py
python -m pytest  test\test_ui_dialogs.py test\test_viewer_main_windows.py
python -m pytest test
```

**Comment by DanicaSTFC** [comment]
All of the appearances of https://github.com/vais-ral/CILViewer/blob/471c82a81f3b95dd6f177a7890596d9c40f4df22/Wrappers/Python/test/test_viewer_main_windows.py#L67 will open a QApplication. Hence the line   https://github.com/vais-ral/CILViewer/blob/471c82a81f3b95dd6f177a7890596d9c40f4df22/Wrappers/Python/test/test_viewer_main_windows.py#L42 is not compatible with it. This line should be removed
