### ISSUE TITLE
Preserve image spacing and origin when resampling and cropping images

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CILViewer#94]
Currently the BaseResampleReader and BaseCroppedReader in conversion.py do not preserve the original origin and spacing of the image file.

In the resample reader the new image spacing needs to be the downsampled spacing multiplied by the original image spacing. The new origin needs to be the original origin -0.5 to center the slices correctly.

**Comment by paskino** [comment]
I suppose the origin should be `-0.5 * slice_thickness`, i.e. `1/spacing`.

**Comment by lauramurgatroyd** [comment]
Since our discussion yesterday the above comment re: the origin is now incorrect. The new origin should be: 

origin_resampled = (1 - spacing) * 0.5 + origin_orig

as discussed here: https://github.com/vais-ral/CCPi-DVC/issues/109
