### ISSUE TITLE
conversion of image to world coordinates is not correct

### ISSUE THREAD

**Issue by paskino** [vais-ral/CILViewer#98]
Given an image with known `spacing` and `origin` the world coordinate and viceversa operation should be obtained by

```python

world_coordinates = [ image_coordinates[i] * spacing[i] + origin[i] for i in range(3)]
image_coordinates= [(world_coordinates[i] / spacing[i]) - origin[i]  for i in range(3)]
```

The viewer calculates both [wrongly](https://github.com/vais-ral/CILViewer/blob/master/Wrappers/Python/ccpi/viewer/CILViewer2D.py#L908) as 
```python
world_coordinates = [(image_coordinates[i] - origin[i]) * spacing[i]  for i in range(3)]
```

Analogously, the world to image coordinate needs fixing, it should be 

```python
img_coords = [(world_coordinates[i] + origin[i] ) / spacing[i]  for i in range(3)]
```

**Comment by lauramurgatroyd** [comment]
Say for example we have an image with origin [1,1,1]. Does that not mean that we want [1,1,1] to appear at [0,0,0] in the world? (hence we subtract the origin to make that translation)? That's how I understood it was working, and I made the clipping planes to be consistent with that.

**Comment by paskino** [comment]
No, I believe that you want to position your image anywhere in the world, not just in the origin. 

Example: imagine you want to put on your scene a downsampled image and a cropped version of the original. How do you match them? You can shift them with origin.
